# Generated by Django 5.0.7 on 2026-05-31 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=180, verbose_name='nome completo')),
                ('study_area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('ambos', 'Ambos'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='área de estudo')),
                ('college', models.CharField(blank=True, max_length=180, verbose_name='faculdade')),
                ('objective', models.CharField(blank=True, max_length=220, verbose_name='objetivo')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do usuário',
                'verbose_name_plural': 'Perfis dos usuários',
            },
        ),
    ]
