# Generated by Django 5.0.7 on 2026-05-31 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(max_length=140)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulado',
                'verbose_name_plural': 'Simulados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('material_type', models.CharField(choices=[('resumo', 'Resumo'), ('questao', 'Questão'), ('transcricao', 'Transcrição'), ('flashcard', 'Flashcard'), ('simulado', 'Simulado'), ('plano', 'Plano de estudos')], max_length=30)),
                ('file_format', models.CharField(choices=[('docx', 'Word'), ('pdf', 'PDF'), ('txt', 'TXT')], max_length=10)),
                ('file', models.FileField(upload_to='exports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportação',
                'verbose_name_plural': 'Exportações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=20)),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.folder')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('material_type', models.CharField(choices=[('resumo', 'Resumo'), ('questao', 'Questão'), ('transcricao', 'Transcrição'), ('flashcard', 'Flashcard'), ('simulado', 'Simulado'), ('plano', 'Plano de estudos')], max_length=30)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('content', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item da biblioteca',
                'verbose_name_plural': 'Itens da biblioteca',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(max_length=140)),
                ('statement', models.TextField()),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=20)),
                ('question_type', models.CharField(choices=[('multipla', 'Múltipla escolha'), ('vf', 'Verdadeiro ou falso'), ('discursiva', 'Discursiva'), ('caso_juridico', 'Caso prático jurídico'), ('caso_clinico', 'Caso clínico médico')], default='multipla', max_length=30)),
                ('favorite', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='studies.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.question')),
            ],
            options={
                'verbose_name': 'Resposta do simulado',
                'verbose_name_plural': 'Respostas dos simulados',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='studies.question'),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('course', models.CharField(blank=True, max_length=140)),
                ('subjects', models.TextField(help_text='Uma matéria por linha')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('daily_minutes', models.PositiveIntegerField(default=60)),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=20)),
                ('objective', models.CharField(choices=[('faculdade', 'Prova da faculdade'), ('oab', 'OAB'), ('residencia', 'Residência'), ('concurso', 'Concurso'), ('revisao', 'Revisão geral')], default='faculdade', max_length=30)),
                ('content', models.TextField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de estudos',
                'verbose_name_plural': 'Planos de estudos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('source_type', models.CharField(default='assunto_digitado', max_length=40)),
                ('summary_type', models.CharField(choices=[('curto', 'Curto'), ('medio', 'Médio'), ('completo', 'Completo'), ('prova', 'Para prova'), ('simples', 'Explicação simples'), ('mapa_mental', 'Mapa mental em texto'), ('vespera', 'Revisão de véspera')], default='medio', max_length=30)),
                ('level', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='intermediario', max_length=30)),
                ('input_text', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('favorite', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumo',
                'verbose_name_plural': 'Resumos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('direito', 'Direito'), ('medicina', 'Medicina'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/transcriptions/')),
                ('raw_text', models.TextField(blank=True, help_text='Texto bruto retornado pela transcrição.')),
                ('professor_text', models.TextField(blank=True, help_text='Transcrição limpa/fiel da fala do professor, sem resumo.')),
                ('summary_text', models.TextField(blank=True, help_text='Resumo automático da aula gerado a partir da transcrição.')),
                ('corrected_text', models.TextField(blank=True)),
                ('topics_text', models.TextField(blank=True)),
                ('status', models.CharField(default='concluida', max_length=30)),
                ('favorite', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcrição',
                'verbose_name_plural': 'Transcrições',
                'ordering': ['-created_at'],
            },
        ),
    ]
